export const ADD_BREADCRUMB = 'ADD_BREADCRUMB';
export const ADD_BASIC_INFORMATION = 'ADD_BASIC_INFORMATION';
export const ADD_DRIVER_INFORMATION = 'ADD_DRIVER_INFORMATION';
export const ADD_INVOLVED_VEHICLE = 'ADD_INVOLVED_VEHICLE';
export const ADD_PEOPLE_IN_INVOLVED_VEICLE = 'PEOPLE_IN_INVOLVED_VEHICLE';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADD_REGISTRATION_BASIC_INFORMATION = 'ADD_REGISTRATION_BASIC_INFORMATION';
export const ADD_USER_TYPE = 'ADD_USER_TYPE';
export const TRAFFICS = 'TRAFFICS';
export const ACCIDENTS = 'ACCIDENTS';
export const CLEAR_ACCIDENTS = 'CLEAR_ACCIDENTS';
export const ACCIDENT_ONLY = 'ACCIDENT_ONLY';
export const CLEAR_ACCIDENT_ONLY = 'CLEAR_ACCIDENT_ONLY';

