export const ADD_BREADCRUMB = 'ADD_BREADCRUMB';
export const ADD_BASIC_INFORMATION = 'ADD_BASIC_INFORMATION';
export const ADD_DRIVER_INFORMATION = 'ADD_DRIVER_INFORMATION';
export const ADD_INVOLVED_VEHICLE = 'ADD_INVOLVED_VEHICLE';
export const ADD_PEOPLE_IN_INVOLVED_VEICLE = 'PEOPLE_IN_INVOLVED_VEHICLE';
